---
title: Kyle Tress
url: http://tress.siteleaf.net
timezone: UTC
collections:
  books:
    title: Books
    output: true
  races:
    title: Races
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalinks: pretty
